from .gpt_image_size_calculator import (
    GptImageSizeCalculator,
    NODE_CLASS_MAPPINGS as CALCULATOR_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CALCULATOR_DISPLAY_NAME_MAPPINGS,
)
from .auto_geometry import AUTO_NODE_CLASS_MAPPINGS, AUTO_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**CALCULATOR_CLASS_MAPPINGS, **AUTO_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {
    **CALCULATOR_DISPLAY_NAME_MAPPINGS,
    **AUTO_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["GptImageSizeCalculator", "NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
